# Generated by Django 4.0.3 on 2022-03-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, unique=True)),
                ('user_pw', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=30)),
                ('validation', models.BooleanField(default=False)),
            ],
        ),
    ]
